name 'cpe_gorilla'
maintainer 'Uber Technologies, Inc.'
maintainer_email 'noreply@uber.com'
license 'Apache-2.0'
description 'This cookbook manages and installs gorilla.'
version '0.1.0'
chef_version '>= 14.14'
supports 'windows'

depends 'cpe_utils'
depends 'cpe_remote'
