name 'cpe_workspaceone'
maintainer 'Uber Technologies, Inc.'
maintainer_email 'noreply@uber.com'
license 'Apache-2.0'
description 'Installs/Configures cpe_workspaceone'
version '0.1.0'
chef_version '>= 14.14'
supports 'mac_os_x'

depends 'cpe_remote'
depends 'cpe_utils'
depends 'uber_helpers'
