name 'cpe_umad'
maintainer 'Uber Technologies, Inc.'
maintainer_email 'noreply@uber.com'
license 'Apache-2.0'
description 'This cookbook manages and installs umad.'
version '0.1.0'
chef_version '>= 14.14'

depends 'cpe_launchd'
depends 'cpe_utils'
