name 'cpe_zoom'
maintainer 'Uber Technologies, Inc.'
maintainer_email 'noreply@uber.com'
license 'Apache-2.0'
description 'Installs/Configures cpe_zoom'
version '0.1.0'
chef_version '>= 14.14'

depends 'cpe_profiles'
depends 'cpe_utils'
depends 'uber_helpers'
