name 'cpe_osquery'
maintainer 'Uber Technologies, Inc.'
maintainer_email 'noreply@uber.com'
license 'Apache-2.0'
description 'Installs/Configures osquery'
version '0.1.0'
chef_version '>= 14.14'

depends 'cpe_remote'
depends 'cpe_utils'
