name 'cpe_nudge'
maintainer 'Uber Technologies, Inc.'
maintainer_email 'noreply@uber.com'
license 'All Rights Reserved'
description 'This cookbook manages and installs nudge.'
version '0.1.0'
chef_version '>= 14.14'

depends 'cpe_launchd'
depends 'cpe_remote'
depends 'cpe_utils'
depends 'uber_helpers'
